import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import os
import sys

# Ensure this script can import from app
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from app.models.fusion_model import FusionMLP

def generate_synthetic_data(num_samples=10000):
    """
    Generate synthetic data based on the heuristic rules to train the fusion MLP.
    In a real scenario, this data would come from historically labeled video clips.
    """
    weapons = np.random.rand(num_samples, 1).astype(np.float32)
    fights = np.random.rand(num_samples, 1).astype(np.float32)
    screams = np.random.rand(num_samples, 1).astype(np.float32)
    
    # We will simulate audio_emb (dim=1024). 
    # To allow the network to learn the 'scream' rule, we embed the scream score 
    # directly into the first feature of the embedding as a proxy.
    audio_embs = np.random.rand(num_samples, 1024).astype(np.float32) * 0.1
    audio_embs[:, 0] = screams[:, 0]
    
    labels = []
    
    for i in range(num_samples):
        w = weapons[i, 0]
        f = fights[i, 0]
        s = screams[i, 0]
        
        # Ground truth generated by human-defined heuristic rules
        if w > 0.5 or f > 0.6:
            labels.append(2) # High
        elif s > 0.5:
            labels.append(1) # Medium
        elif w > 0.3 or f > 0.3 or s > 0.3:
            labels.append(1) # Medium
        else:
            labels.append(0) # Low
            
    labels = np.array(labels, dtype=np.int64)
    return torch.tensor(weapons), torch.tensor(fights), torch.tensor(audio_embs), torch.tensor(labels)

def train():
    print("Generating synthetic data (10,000 samples)...")
    train_w, train_f, train_a, train_y = generate_synthetic_data(10000)
    
    model = FusionMLP(audio_emb_size=1024, hidden_size=64, num_classes=3)
    
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.002)
    
    epochs = 20
    batch_size = 64
    num_batches = len(train_y) // batch_size
    
    print("Training FusionMLP...")
    for epoch in range(epochs):
        model.train()
        total_loss = 0
        correct = 0
        
        for i in range(num_batches):
            start_idx = i * batch_size
            end_idx = start_idx + batch_size
            
            w_batch = train_w[start_idx:end_idx]
            f_batch = train_f[start_idx:end_idx]
            a_batch = train_a[start_idx:end_idx]
            y_batch = train_y[start_idx:end_idx]
            
            optimizer.zero_grad()
            
            # Forward pass: weapon, fight, audio_emb
            outputs = model(w_batch, f_batch, a_batch)
            loss = criterion(outputs, y_batch)
            
            loss.backward()
            optimizer.step()
            
            total_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            correct += (predicted == y_batch).sum().item()
            
        accuracy = correct / len(train_y)
        if (epoch + 1) % 5 == 0 or epoch == 0:
            print(f"Epoch {epoch+1}/{epochs}, Loss: {total_loss/num_batches:.4f}, Accuracy: {accuracy*100:.2f}%")
        
    os.makedirs('ml_models', exist_ok=True)
    save_path = 'ml_models/fusion_weights.pt'
    torch.save(model.state_dict(), save_path)
    print(f"\nModel strictly trained to mimic heuristic rules!")
    print(f"Weights successfully saved to {save_path}")

if __name__ == "__main__":
    train()
